# Álgebra Básica

In [1]:
# Import Numpy
import numpy as np

In [2]:
# Criando arrays
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12],[13,14,15]])

print("Array a")
print(a,a.shape)
print("")
print("Array b")
print(b,b.shape)

Array a
[[1 2 3]
 [4 5 6]] (2, 3)

Array b
[[ 7  8  9]
 [10 11 12]
 [13 14 15]] (3, 3)


In [3]:
# Transformando as arrays em matrizes
matrix_a = np.matrix(a)
matrix_b = np.matrix(b)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [4]:
# Multiplicando Matrizes
matMult = np.matmul(a,b)

print("Matrizes Multiplicadas")
print(matMult)

Matrizes Multiplicadas
[[ 66  72  78]
 [156 171 186]]


In [5]:
# Mostrando valores das Matrizes

print("Array a Original")
print(a)

#Apenas a primeira linha
print("")
print("Primeira Linha de a")
print(a[0])

#Apenas a primeira coluna
print("")
print("Primeira Coluna de a")
print(a[:,0])

#Apenas a última linha
print("")
print("Última Linha de a")
print(a[-1])

#Apenas a última coluna
print("")
print("Última coluna de a")
print(a[:, -1])

# a com linhas invertidas
print("")
print("Invertendo a ordem das linhas")
print(a[::-1])

# a com colunas invertidas
print("")
print("Invertendo a ordem das colunas")
print(a[:,::-1])

# a com linhas e colunas invertidas
print("")
print("Invertendo a ordem das linhas e colunas")
print(a[::-1,::-1])

# Pulando a cada 2 posições
print("")
print("Pulando 2 posições")
print(a[:,::2])

Array a Original
[[1 2 3]
 [4 5 6]]

Primeira Linha de a
[1 2 3]

Primeira Coluna de a
[1 4]

Última Linha de a
[4 5 6]

Última coluna de a
[3 6]

Invertendo a ordem das linhas
[[4 5 6]
 [1 2 3]]

Invertendo a ordem das colunas
[[3 2 1]
 [6 5 4]]

Invertendo a ordem das linhas e colunas
[[6 5 4]
 [3 2 1]]

Pulando 2 posições
[[1 3]
 [4 6]]


In [6]:
# Criando vetor de Zeros
zeros = np.zeros(3,dtype= "int32")
print("Vetor de Zeros")
print(zeros)

print("")
# Criando vetor de Uns
uns = np.ones(3, dtype= "int32")
print("Vetor de Uns")
print(uns)

print("")
# Preenchendo com outros valores
outros = np.full([3,3], 3) #Cria uma matriz 3x3 cheia de valores 3
print("Valores Diversos")
print(outros)

print("")
# Preenchendo com valores aleatórios
aleatorios = np.random.randint(0, 16, size=(3, 3)) #Cria uma matriz 3x3 aleatoria
print("Valores Aleatorios")
print(aleatorios)

Vetor de Zeros
[0 0 0]

Vetor de Uns
[1 1 1]

Valores Diversos
[[3 3 3]
 [3 3 3]
 [3 3 3]]

Valores Aleatorios
[[ 4 12  5]
 [13  3  1]
 [ 6  2 15]]


In [7]:
#Matriz Identidade
print("Identidade")
np.identity(4, dtype='int32')


# Matriz Identidade
print("Identidade")
np.identity(4, dtype='int32')

Identidade
Identidade


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

# Aplicações Avançadas e Estatística Básica

In [8]:
import math

# Pi
math.pi

3.141592653589793

In [9]:
# Encontrando o Determinante de Matrizes

matriz = np.array([[1,2,3], [6,57,2], [7,12,3.3233]])
print(matriz)

determinante = np.linalg.det(matriz)
print(f"Determinante = {determinante}")

[[ 1.      2.      3.    ]
 [ 6.     57.      2.    ]
 [ 7.     12.      3.3233]]
Determinante = -827.4515


In [10]:
# Estatística Básica
dados = np.random.randint(0,100, size=(5,5))
dados

array([[ 5, 42, 69, 84, 93],
       [33, 74, 85, 53,  2],
       [33,  2, 89, 47, 54],
       [80,  8, 38, 90, 69],
       [44, 18, 92, 30, 92]], dtype=int32)

In [11]:
print(f"Valor Mínimo = {np.min(dados)}")
print(f"Menores Valores por Coluna = {np.min(dados, axis=0)}")
print(f"Menores Valores por Linha = {np.min(dados, axis=1)}")
print(f"Valor Máximo = {np.max(dados)}")
print(f"Soma dos Valores = {np.sum(dados)}")
print(f"Soma dos Valores por Coluna = {np.sum(dados, axis=0)}")
print(f"Soma dos Valores por Linha = {np.sum(dados, axis=1)}")
print(f"Média dos Valores = {np.average(dados)}")
print(f"Média dos Valores por Coluna = {np.average(dados, axis=0)}")
print(f"Média dos Valores por Linha = {np.average(dados, axis=1)}")

Valor Mínimo = 2
Menores Valores por Coluna = [ 5  2 38 30  2]
Menores Valores por Linha = [ 5  2  2  8 18]
Valor Máximo = 93
Soma dos Valores = 1326
Soma dos Valores por Coluna = [195 144 373 304 310]
Soma dos Valores por Linha = [293 247 225 285 276]
Média dos Valores = 53.04
Média dos Valores por Coluna = [39.  28.8 74.6 60.8 62. ]
Média dos Valores por Linha = [58.6 49.4 45.  57.  55.2]


In [12]:
#Reshape

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# vstack junta um acima do outro
print("vstack")
c = np.vstack([b,a,b])
print(c)

# hstack junta um ao lado do outro
print("")
print("hstack")
d = np.hstack([b,a,b])
print(d)

#Mesclando os dois
e = np.vstack([a,b])
f = np.vstack([b,a])

print("vstack 1","\n", e,"\n","\n","vstack 2","\n",f)

g = np.hstack([e,f])
print("\n", "hstack","\n",g)

vstack
[[5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]

hstack
[5 6 7 8 1 2 3 4 5 6 7 8]
vstack 1 
 [[1 2 3 4]
 [5 6 7 8]] 
 
 vstack 2 
 [[5 6 7 8]
 [1 2 3 4]]

 hstack 
 [[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]]


In [14]:
np.tile(a, 4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])